# --- Essentials
brew "git"
brew "gh"
brew "go"
brew "curl"
brew "wget"
brew "jq"
brew "sevenzip"
brew "bat"
brew "tree"
brew "fd"
brew "ripgrep"
brew "mas"
brew "fx"

# --- Shell / terminal workflow
brew "tmux"
brew "powerlevel10k"
brew "btop"
brew "fastfetch"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# --- Android / Kotlin / iOS
brew "kotlin"
brew "ktlint"
brew "detekt"
brew "cocoapods"

# --- JS / RN toolchain
brew "mise"
brew "nvm"
brew "pnpm"
brew "yarn"
brew "typescript"
brew "watchman"

# --- DevOps / local services
brew "lazygit"
brew "lazydocker"
brew "redis"
brew "jfrog-cli"
brew "firebase-cli"
brew "gemini-cli"
brew "pre-commit"

# --- Docs
brew "pandoc"
brew "mdv"
brew "markdown"

# --- Apps
cask "antigravity"
cask "antigravity-cli"
cask "antigravity-ide"
cask "bettercapture"
cask "brave-browser"
cask "chatgpt"
cask "codex"
cask "codexbar"
cask "conductor"
cask "docker-desktop"
cask "figma"
cask "google-gemini"
cask "insomnia"
cask "iterm2"
cask "miaoyan"
cask "minisim"
cask "mockoon"
cask "nordvpn"
cask "spotify"
cask "temurin@8"
cask "tor-browser"
cask "zed"
